### ISSUE TITLE
Не отображает пары 20:25-22:00

### ISSUE THREAD

**Issue by arthurchumak** [vmakoed/bsuir-schedule-complete#4]
![image](https://cloud.githubusercontent.com/assets/8324045/18013286/07e03776-6bc6-11e6-8121-0e267cc8bef2.png)
замечено на группе 353502

**Comment by vmakoed** [comment]
[fixed](https://github.com/vmakoed/bsched/commit/824382590e98a65164ba0b1c970e7bd78a09be4e)
